// exercicios-WEB/react/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react'
import './Calculator.css'
import Button from '../components/Button'
import Display from '../components/Display'

const initialState = {
  displayValue: '0',
  clearDisplay: false,
  operation: null,
  values: [0, 0],
  current: 0
}

export default class Calculator extends Component {
  state = { ...initialState }

  constructor(props) {
    super(props)
    this.clearMemory = this.clearMemory.bind(this)
    this.setOperation = this.setOperation.bind(this)
    this.addDigit = this.addDigit.bind(this)
  }
  clearMemory() {
    this.setState({ ...initialState })
  }
  setOperation(operation) {
    if (this.state.current === 0) {
      // this.state.current = 1
      // this.state.clearDisplay = true;
      // this.state.operation = operation
      this.setState({ operation, current: 1, clearDisplay: true })
    } else {
      const equals = operation === '='
      const currentOperation = this.state.operation

      const values = { ...this.state.values }

      try {
        values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`)
      } catch (error) {
        values[0] = this.state.values[0]
      }
      values[1] = 0

      this.setState({
        displayValue: values[0],
        operation: equals ? null : operation,
        current: equals ? 0 : 1,
        clearDisplay: !equals,
        values
      })
    }
  }
  addDigit(n) {
    if (n === '.' && this.state.displayValue.includes('.')) {
      return
    }
    const clearDisplay =
      this.state.displayValue === '0' || this.state.clearDisplay
    const currentValue = clearDisplay ? '' : this.state.displayValue
    const displayValue = currentValue + n
    this.setState({ displayValue, clearDisplay: false })

    if (n !== '.') {
      const i = this.state.current
      const newValue = parseFloat(displayValue)
      //const values = [...this.state.values]
      const values = this.state.values
      values[i] = newValue
      this.setState({ values })
      console.log(values)
    }
  }

  render() {
    return (
      <div className="calculator">
        <Display value={this.state.displayValue} />
        <Button label="AC" click={this.clearMemory} triple />
        <Button label="/" click={this.setOperation} operation />
        <Button label="7" click={this.addDigit} />
        <Button label="8" click={this.addDigit} />
        <Button label="9" click={this.addDigit} />
        <Button label="*" click={this.setOperation} operation />
        <Button label="4" click={this.addDigit} />
        <Button label="5" click={this.addDigit} />
        <Button label="6" click={this.addDigit} />
        <Button label="-" click={this.setOperation} operation />
        <Button label="1" click={this.addDigit} />
        <Button label="2" click={this.addDigit} />
        <Button label="3" click={this.addDigit} />
        <Button label="+" click={this.setOperation} operation />
        <Button label="0" click={this.addDigit} double />
        <Button label="." click={this.addDigit} />
        <Button label="=" click={this.setOperation} operation />
      </div>
    )
  }
}

// exercicios-WEB/vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
    <Display :value="displayValue" />
    <Button label="AC" triple @onClick="ClearMemory" />
    <Button label="/" operation @onClick="SetOperation" />
    <Button label="7" @onClick="AddDigit" />
    <Button label="8" @onClick="AddDigit" />
    <Button label="9" @onClick="AddDigit" />
    <Button label="*" operation @onClick="SetOperation" />
    <Button label="4" @onClick="AddDigit" />
    <Button label="5" @onClick="AddDigit" />
    <Button label="6" @onClick="AddDigit" />
    <Button label="-" operation @onClick="SetOperation" />
    <Button label="1" @onClick="AddDigit" />
    <Button label="2" @onClick="AddDigit" />
    <Button label="3" @onClick="AddDigit" />
    <Button label="+" operation @onClick="SetOperation" />
    <Button label="0" double @onClick="AddDigit" />
    <Button label="." @onClick="AddDigit" />
    <Button label="=" operation @onClick="SetOperation" />
  </div>
</template>

<script>
import Display from '../components/Display';
import Button from '../components/Button';
export default {
  components: { Button, Display },
  data: function() {
    return {
      displayValue: '0',
      clearDisplay: false,
      operation: null,
      values: [0, 0],
      currentIndex: 0,
    };
  },
  methods: {
    ClearMemory() {
      Object.assign(this.$data, this.$options.data());
    },
    SetOperation(operation) {
      if (this.currentIndex === 0) {
        this.operation = operation;
        this.currentIndex = 1;
        this.clearDisplay = true;
      } else {
        const equals = operation === '=';
        const currentOperation = this.operation;

        try {
          this.values[0] = eval(
            `${this.values[0]} ${currentOperation} ${this.values[1]}`
          );
        } catch (error) {
          this.$emit('onError', error);
        }
        this.values[1] = 0;
        this.displayValue = this.values[0];
        this.operation = equals ? null : operation;
        this.currentIndex = equals ? 0 : 1;
        this.clearDisplay = !equals;
      }
    },
    AddDigit(n) {
      if (n === '.' && this.displayValue.includes('.')) {
        return;
      }

      const clearDisplay = this.displayValue === '0' || this.clearDisplay;
      const currentValue = clearDisplay ? '' : this.displayValue;
      const displayValue = currentValue + n;

      this.displayValue = displayValue;
      this.clearDisplay = false;

      // if (n !== '.') {
      //   const i = this.currentIndex;
      //   const newValue = parseFloat(displayValue);
      //   this.values[i] = newValue;
      // }

      this.values[this.currentIndex] = displayValue;
    },
  },
};
</script>

<style>
.calculator {
  height: 480px;
  width: 335px;
  border-radius: 5px;
  overflow: hidden;
  display: grid;
  grid-template-columns: repeat(4, 25%);
  grid-auto-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>
